name: makefile-ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup PHP
      # Action gives to setup the PHP environment to test application
      # https://github.com/shivammathur/setup-php
      uses: shivammathur/setup-php@v2
      with:
        # Specify the PHP version
        php-version: '7.4'
    - name: Install
      # Install project
      run: make install
    
    - name: linter
      run: make lint
